### ISSUE TITLE
`too many SQL variables` occurs

### ISSUE THREAD

**Issue by tbigot** [HadrienG/taxadb#4]
I frequently encounter a `too many SQL variables` issue, for instance when trying to create my up-to-date db:

```shell
$ taxadb create -i taxadb --dbname taxadb
parsed nodes
parsed names
merge successful
usage: taxadb <command> [options]

download and create the database used by the taxadb library

optional arguments:
  -h, --help  show this help message and exit

available commands:
  
    download  download the files required to create the database
    create    build the database
    query     query the database

too many SQL variables
```

It also occurs when I query  accession db with large (but no so large) lists:
```python
accession.taxid(accs, args.taxadb, Prot))
```
I have to split `accs` in sublists and hence get lists of generators.

Shouldn’t query be done one-by-one, or at least by packets of a number lower than `SQLITE_MAX_LENGTH`?

Thanks in advance!

**Comment by HadrienG** [comment]
Hi,

Thanks for the bug report!
It should have been fixed in 0.5.0 😉

**Comment by treitpeter** [comment]
Hi Hadrien,

I am also having this issue when I try to create the database.

! taxadb create -i taxadb1 --dbname taxadb1.sqlite3

INFO:taxadb.app:Creating table taxa
INFO:taxadb.app:Parsing files
INFO:taxadb.parser.TaxaDumpParser:Parsed nodes.dmp
INFO:taxadb.parser.TaxaDumpParser:Parsed names.dmp
INFO:taxadb.app:Inserting taxonomy data

INFO:taxadb.app: 0 chunks [00:00, ? chunks/s]
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: too many SQL variables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\taxadb.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\lib\site-packages\taxadb\app.py", line 352, in main
    args.func(args)
  File "d:\anaconda\lib\site-packages\taxadb\app.py", line 124, in create_db
    Taxa.insert_many(taxa_info_list[i:i+args.chunk]).execute()
  File "d:\anaconda\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "d:\anaconda\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "d:\anaconda\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "d:\anaconda\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "d:\anaconda\lib\site-packages\peewee.py", line 127, in reraise
    raise value.with_traceback(tb)
  File "d:\anaconda\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: too many SQL variables

Any directions as to how I might solve this? 

Best, 

Peter

**Comment by HadrienG** [comment]
Thanks for commenting on this. I'll reopen the issue and check it out.

**Comment by treitpeter** [comment]
Dear Hadrien,

I am currently on holiday but will get on this ASAP when I’m back. Thanks
for the speedy help!!

Peter

**Comment by HadrienG** [comment]
Hi!

in the new release (`0.10.0`) `taxadb` will throw an error and tell you to lower the chunk size instead of crash.
